### PR TITLE
Add comment and some documentation

### PR DESCRIPTION
**Pull request by aileo**
First step to get some doc

@JohnBerd, would you review it and tell me what you think about it ?

### CODE REVIEW

**Comment by JohnBerd** [comment]
The documentation concerning the example is very clear, and the README gives now a minimal overview of the project. Everything is okay to me.

**Comment by aileo** [comment]
Added some more, @JohnBerd may I ask for another review ?

**Comment by JohnBerd** [comment]
@aileo, sure, everything is good to me!

**Comment by aileo** [comment]
I will merge then and I think it closes #1

**Pull request merged**
